version: '3.4'

networks:
  cubaleon:
    external:
      name: proxy_cubaleon

services:
  php_prestashop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-prestashop
    restart: always
    networks:
      - cubaleon
    volumes:
      - .:/usr/share/prestashop
    env_file:
      - env/development
    environment:
      - VIRTUAL_HOST=test.cuba-web.com,www.test.cuba-web.com
      - LETSENCRYPT_HOST=test.cuba-web.com,www.test.cuba-web.com
      - LETSENCRYPT_EMAIL=miltonleon86@gmail.com
